name: Deploy Portfolio (без Docker Hub)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: portfolio-source
          path: .

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: portfolio-source
          path: ./portfolio-source

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: "83.172.43.115"
          username: ${{ secrets.SSH_USER }}
          key: "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACBSPscemH+VG1RdIiJC9116YmGV+niexr3MBnxulreMPgAAAJD6qu43+qruNwAAAAtzc2gtZWQyNTUxOQAAACBSPscemH+VG1RdIiJC9116YmGV+niexr3MBnxulreMPgAAAEDA2lAjv048dfDBbQX/Fc/XWHQ9aRKHPFFxLYAk+0OtRFI+xx6Yf5UbVF0iIkL3XXpiYZX6eJ7GvcwGfG6Wt4w+AAAADHJvb3RAYW5zaWJsZQE=-----END OPENSSH PRIVATE KEY-----"
          port: 22
          script: |
            echo "Connected successfully!"
            cd /opt/my-port
            git pull origin main
            docker-compose down
            docker-compose up -d --build
