name: Deploy Portfolio (без Docker Hub)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем всю историю коммитов

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no \
              ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
              "echo 'SSH connection successful!'"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_timeout: 15m
          script: |
            echo "=== Starting deployment ==="
            cd /opt/my-port || exit 1

            # Обновляем репозиторий
            git fetch origin
            git reset --hard origin/main

            # Пересобираем и запускаем контейнеры
            docker compose down
            docker compose pull || true
            docker compose build --no-cache
            docker compose up -d

            echo "=== Deployment completed successfully ==="
            docker ps
